// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.enabled", true);
user_pref("app.normandy.user_id", "5e7466b1-dc92-41d3-b0fe-b84873a6d20c");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 3556);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1571936056);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 86);
user_pref("browser.newtabpage.activity-stream.impressionId", "{33a4ff3a-8e6a-46b6-984b-f424b4b16744}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1572981589873");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1572983380873");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1572981577075");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1572985177075");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191002193559");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20191002193559");
user_pref("browser.startup.homepage_override.mstone", "69.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1572981574);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1571936059037");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "69.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "25b6977983534d5e85b3beab2744b8b7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191002193559");
user_pref("extensions.lastAppVersion", "69.0.2");
user_pref("extensions.lastPlatformVersion", "69.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"3fcb5985-1022-4791-957b-1e5ef0a88c1b\",\"fxmonitor@mozilla.org\":\"b7c0ee19-9876-4008-b0d6-815c914dbfbd\",\"screenshots@mozilla.org\":\"1fcac948-4ecf-4d09-aa14-fdedd72f75a7\",\"webcompat-reporter@mozilla.org\":\"bdf5d7a1-148b-461c-80a9-b766930d71ad\",\"webcompat@mozilla.org\":\"ebd86417-7656-4489-ac68-6dd8d4885490\",\"default-theme@mozilla.org\":\"6553a1ab-14c0-489d-83f5-8efaeb1ebf86\",\"google@search.mozilla.org\":\"2a54e3e4-6ab4-4c3b-a29a-da6d76a88ff0\",\"amazondotcom@search.mozilla.org\":\"3bdd2e43-4c29-496d-b583-11a55f32ae29\",\"bing@search.mozilla.org\":\"50befcc3-89d7-4805-9360-3a4bde8476f5\",\"ddg@search.mozilla.org\":\"3c8bf693-0525-4398-a5d9-b4834c91db83\",\"ebay@search.mozilla.org\":\"744420d5-bc5c-4a88-ab07-5c4d9227efe5\",\"twitter@search.mozilla.org\":\"1dcf3cd8-d8ab-45d6-aaf8-ad52c173da34\",\"wikipedia@search.mozilla.org\":\"6c5de6a8-dc13-4f4c-bd66-4bbc17a18360\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "dc72eb1a-f47d-4b86-b1a7-4a8b1459859d");
user_pref("security.sandbox.plugin.tempDirSuffix", "b2f747d7-3e03-4555-b1c5-d0776bf4b6b7");
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1572981573);
user_pref("toolkit.telemetry.cachedClientID", "2e5630f3-3cec-4d9c-8c8e-adecf0b4c508");
user_pref("toolkit.telemetry.previousBuildID", "20191002193559");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
